# -*- coding: utf-8 -*-

from gettext import gettext as _

LEVEL1 = [
        2,
        _('Cities'),
        ['lineasDepto', 'capitales', 'ciudades'],
        [],
[
    (_('Kigali'), _("It's in %s") % _('Kigali')),
    (_('Nyanza'), _("It's in %s") % _('Southern Province')),
    (_('Kibuye'), _("It's in %s") % _('Western Province')),
    (_('Byumba'), _("It's in %s") % _('Northern Province')),
    (_('Rwamagana'), _("It's in %s") % _('Eastern Province')),
    (_('Kicukiro'), _("It's in %s") % _('Kigali')),
    (_('Butamwa'), _("It's in %s") % _('Kigali')),
    (_('Ngaru'), _("It's in %s") % _('Southern Province')),
    (_('Kiyumba'), _("It's in %s") % _('Southern Province')),
    (_('Runda'), _("It's in %s") % _('Southern Province')),
    (_('Bulinga'), _("It's in %s") % _('Southern Province')),
    (_('Gitarama'), _("It's in %s") % _('Southern Province')),
    (_('Masango'), _("It's in %s") % _('Southern Province')),
    (_('Ruhango'), _("It's in %s") % _('Southern Province')),
    (_('Gatagara'), _("It's in %s") % _('Southern Province')),
    (_('Rusatira'), _("It's in %s") % _('Southern Province')),
    (_('Kaduha'), _("It's in %s") % _('Southern Province')),
    (_('Karaba'), _("It's in %s") % _('Southern Province')),
    (_('Gikongoro'), _("It's in %s") % _('Southern Province')),
    (_('Karama'), _("It's in %s") % _('Southern Province')),
    (_('Kitabi'), _("It's in %s") % _('Southern Province')),
    (_('Butare'), _("It's in %s") % _('Southern Province')),
    (_('Gisagara'), _("It's in %s") % _('Southern Province')),
    (_('Ruramba'), _("It's in %s") % _('Southern Province')),
    (_('Busoro'), _("It's in %s") % _('Southern Province')),
    (_('Munini'), _("It's in %s") % _('Southern Province')),
    (_('Runyombyi'), _("It's in %s") % _('Southern Province')),
    (_('Kagitumba'), _("It's in %s") % _('Eastern Province')),
    (_('Rwemhasha'), _("It's in %s") % _('Eastern Province')),
    (_('Lubirizi'), _("It's in %s") % _('Eastern Province')),
    (_('Nyagatare'), _("It's in %s") % _('Eastern Province')),
    (_('Muvumba'), _("It's in %s") % _('Eastern Province')),
    (_('Gatunda'), _("It's in %s") % _('Eastern Province')),
    (_('Gabiro'), _("It's in %s") % _('Eastern Province')),
    (_('Ngarama'), _("It's in %s") % _('Eastern Province')),
    (_('Muhura'), _("It's in %s") % _('Eastern Province')),
    (_('Rukara'), _("It's in %s") % _('Eastern Province')),
    (_('Gikoro'), _("It's in %s") % _('Eastern Province')),
    (_('Bicumbi'), _("It's in %s") % _('Eastern Province')),
    (_('Kayonza'), _("It's in %s") % _('Eastern Province')),
    (_('Kigarama'), _("It's in %s") % _('Eastern Province')),
    (_('Kibungo'), _("It's in %s") % _('Eastern Province')),
    (_('Rukira'), _("It's in %s") % _('Eastern Province')),
    (_('Sake'), _("It's in %s") % _('Eastern Province')),
    (_('Bare'), _("It's in %s") % _('Eastern Province')),
    (_('Rusumo'), _("It's in %s") % _('Eastern Province')),
    (_('Kirehe'), _("It's in %s") % _('Eastern Province')),
    (_('Bugesera'), _("It's in %s") % _('Eastern Province')),
    (_('Rilima'), _("It's in %s") % _('Eastern Province')),
    (_('Gashora'), _("It's in %s") % _('Eastern Province')),
    (_('Nemba'), _("It's in %s") % _('Eastern Province')),
    (_('Ngenda'), _("It's in %s") % _('Eastern Province')),
    (_('Butaro'), _("It's in %s") % _('Northern Province')),
    (_('Kidaho'), _("It's in %s") % _('Northern Province')),
    (_('Kirambo'), _("It's in %s") % _('Northern Province')),
    (_('Ruhengeri'), _("It's in %s") % _('Northern Province')),
    (_('Busogo'), _("It's in %s") % _('Northern Province')),
    (_('Cyamba'), _("It's in %s") % _('Northern Province')),
    (_('Mulindi'), _("It's in %s") % _('Northern Province')),
    (_('Nemba'), _("It's in %s") % _('Northern Province')),
    (_('Rushashi'), _("It's in %s") % _('Northern Province')),
    (_('Kinihira'), _("It's in %s") % _('Northern Province')),
    (_('Kinyami'), _("It's in %s") % _('Northern Province')),
    (_('Rutare'), _("It's in %s") % _('Northern Province')),
    (_('Mbogo'), _("It's in %s") % _('Northern Province')),
    (_('Murambi'), _("It's in %s") % _('Northern Province')),
    (_('Shyorongi'), _("It's in %s") % _('Northern Province')),
    (_('Kora'), _("It's in %s") % _('Western Province')),
    (_('Mutura'), _("It's in %s") % _('Western Province')),
    (_('Kagali'), _("It's in %s") % _('Western Province')),
    (_('Gisenyi'), _("It's in %s") % _('Western Province')),
    (_('Nyundo'), _("It's in %s") % _('Western Province')),
    (_('Kabaya'), _("It's in %s") % _('Western Province')),
    (_('Ngororero'), _("It's in %s") % _('Western Province')),
    (_('Mabanza'), _("It's in %s") % _('Western Province')),
    (_('Birambo'), _("It's in %s") % _('Western Province')),
    (_('Bwakira'), _("It's in %s") % _('Western Province')),
    (_('Gishyita'), _("It's in %s") % _('Western Province')),
    (_('Rwamatamu'), _("It's in %s") % _('Western Province')),
    (_('Rwesero'), _("It's in %s") % _('Western Province')),
    (_('Kamembe'), _("It's in %s") % _('Western Province')),
    (_('Cyangugu'), _("It's in %s") % _('Western Province')),
    (_('Cyimbogo'), _("It's in %s") % _('Western Province')),
    (_('Gisakura'), _("It's in %s") % _('Western Province')),
    (_('Rwumba'), _("It's in %s") % _('Western Province')),
    (_('Karengera'), _("It's in %s") % _('Western Province')),
    (_('Nyakabuye'), _("It's in %s") % _('Western Province')),
    (_('Bugumya'), _("It's in %s") % _('Western Province')),
    (_('Bugarama'), _("It's in %s") % _('Western Province'))
]
]

LEVELS = [LEVEL1]

